**Name: Rohan Shrestha**


In [ ]:
import sys

# Check Python version
if sys.version_info.major == 3 and sys.version_info.minor >= 6:
    print("Hello, World!")
    print(f"Python version: {sys.version}")
else:
    print("Please use Python 3.6 or higher.")

Hello, World!
Python version: 3.12.12 (main, Oct 10 2025, 08:52:57) [GCC 11.4.0]


In [ ]:
# Mutable Data Type Example (List)
my_list = [1, 2, 3]
print("Original List:", my_list)

# Modifying the list (changing contents)
my_list.append(4)
print("Modified List:", my_list)

# Immutable Data Type Example (Tuple)
my_tuple = (1, 2, 3)
print("Original Tuple:", my_tuple)

# Trying to modify the tuple (will raise an error)
# my_tuple.append(4)  # Uncommenting this line will raise an AttributeError

Original List: [1, 2, 3]
Modified List: [1, 2, 3, 4]
Original Tuple: (1, 2, 3)


In [ ]:
age = 23  # int
pi = 3.14  # float
temperature = -5.5  # float

print("data type of variable age =", type(age))
print("data type of variable pi =", type(pi))
print("data type of variable temperature =", type(temperature))

data type of variable age = <class 'int'>
data type of variable pi = <class 'float'>
data type of variable temperature = <class 'float'>


In [ ]:
name = "Alice"
greeting = 'Hello'
address = "123 Main St"

print("data type of the variable name =", type(name))
print("data type of the variable greeting =", type(greeting))
print("data type of the variable address =", type(address))

# slice only one element
print("The first letter of the name is:", name[0])
print("The last letter of the name is:", name[-1])

# slice a range of elements
print("The second letter to the fourth of the name is:", name[1:4])
print("The first two letters of the name are:", name[:2])
print("Substring starting from the third letter is:", name[2:])

data type of the variable name = <class 'str'>
data type of the variable greeting = <class 'str'>
data type of the variable address = <class 'str'>
The first letter of the name is: A
The last letter of the name is: e
The second letter to the fourth of the name is: lic
The first two letters of the name are: Al
Substring starting from the third letter is: ice


In [ ]:
list1 = [1, 2, 3, 4]
mixed_list = [12, "Hello", True]

# List is mutable
mixed_list[0] = False
print(mixed_list)

[False, 'Hello', True]


In [ ]:
colors = ('red', 'green', 'yellow', 'blue')
print("First element:", colors[0])
print("Last two elements:", colors[2:])
print("Middle two elements:", colors[1:3])

# colors[0] = 'purple'  # This will generate an error as tuple is immutable

First element: red
Last two elements: ('yellow', 'blue')
Middle two elements: ('green', 'yellow')


In [ ]:
person = {'name': 'John', 'age': 30, 'city': 'Pittsburgh'}
print(f"Hello my name is {person['name']}. I am {person['age']} years old and I live at {person['city']}.")
print("All keys:", list(person.keys()))
print("All values:", list(person.values()))

Hello my name is John. I am 30 years old and I live at Pittsburgh.
All keys: ['name', 'age', 'city']
All values: ['John', 30, 'Pittsburgh']


In [ ]:
person = {'name': 'John', 'age': 30, 'city': 'Pittsburgh'}
print(f"Hello my name is {person['name']}. I am {person['age']} years old and I live at {person['city']}.")
print("All keys:", list(person.keys()))
print("All values:", list(person.values()))

Hello my name is John. I am 30 years old and I live at Pittsburgh.
All keys: ['name', 'age', 'city']
All values: ['John', 30, 'Pittsburgh']


In [ ]:
unique_numbers = {1, 2, 3, 3, 3, 3, 4, 5}
print(unique_numbers)

{1, 2, 3, 4, 5}


In [ ]:
is_student = True
has_license = False

print("data type of the variable is_student =", type(is_student))
print("data type of the variable has_license =", type(has_license))

data type of the variable is_student = <class 'bool'>
data type of the variable has_license = <class 'bool'>


In [ ]:
num = 10

if num > 0:
    print("Positive")
elif num == 0:
    print("Zero")
else:
    print("Non-positive")

Positive


In [ ]:
x = 5
y = 10

if x > 0 and y < 20:
    print("Both conditions are true")

if x > 0 or y > 20:
    print("At least one condition is true")

if not x == 0:
    print("x is not equal to 0")

Both conditions are true
At least one condition is true
x is not equal to 0


In [ ]:
# Define two boolean variables
a = True
b = False

# Using the 'and' operator
if a and b:
    print("Both a and b are True")
else:
    print("Either a or b is False")

# Using the 'or' operator
if a or b:
    print("At least one of a or b is True")
else:
    print("Both a and b are False")

# Using the 'not' operator
if not a:
    print("a is False")
else:
    print("a is True")

Either a or b is False
At least one of a or b is True
a is True


In [ ]:
# for loop:
fruits = ["apple", "banana", "cherry"]
for fruit in fruits:
    print(fruit)

# While loop:
count = 0
while count < 5:
    print("Count is:", count)
    count += 1

# Break
print("loop 1")
for fruit in fruits:
    print(fruit)
    if fruit == "apple":
        break

# Continue
print("loop 2")
for fruit in fruits:
    if fruit == "apple":
        continue
    else:
        print(fruit)

apple
banana
cherry
Count is: 0
Count is: 1
Count is: 2
Count is: 3
Count is: 4
loop 1
apple
loop 2
banana
cherry


In [ ]:
def temperature_converter():
    """
    Converts temperature between Celsius and Fahrenheit.

    This function prompts the user to specify the conversion type
    (Celsius to Fahrenheit or Fahrenheit to Celsius)
    and then asks for the temperature value. It calculates and
    returns the converted temperature.

    Returns:
        float: The converted temperature value.
    """
    print("Choose conversion type:")
    print("1. Celsius to Fahrenheit")
    print("2. Fahrenheit to Celsius")

    # Get conversion choice from user
    choice = input("Enter 1 or 2: ")

    if choice == "1":
        # Celsius to Fahrenheit conversion
        celsius = float(input("Enter temperature in Celsius: "))
        fahrenheit = (celsius * 9/5) + 32
        print(f"{celsius}°C is equal to {fahrenheit}°F")
        return fahrenheit
    elif choice == "2":
        # Fahrenheit to Celsius conversion
        fahrenheit = float(input("Enter temperature in Fahrenheit: "))
        celsius = (fahrenheit - 32) * 5/9
        print(f"{fahrenheit}°F is equal to {celsius}°C")
        return celsius
    else:
        print("Invalid choice. Please enter 1 or 2.")
        return None

# Call the function
temperature_converter()  # Uncomment to run interactively

Choose conversion type:
1. Celsius to Fahrenheit
2. Fahrenheit to Celsius
Enter 1 or 2: 1
Enter temperature in Celsius: 36
36.0°C is equal to 96.8°F


96.8

In [ ]:
# Global Variable Example
x = 10  # Global Variable

def print_global():
    print(x)  # Accessing global variable

print_global()  # Output: 10

# Local Variable Example
def print_local():
    y = 5  # Local variable
    print(y)

print_local()  # Output: 5
# print(y)  # This would cause an error

# Modifying Global Variable
x = 10  # Global variable

def modify_global():
    global x  # Declaring x as global
    x = 20  # Modifying global x

modify_global()
print(x)  # Output: 20

10
5
20


In [ ]:
# Basic try-except
try:
    num = int(input("Enter a number: "))
    print("Result:", 10 / num)
except ZeroDivisionError:
    print("Cannot divide by zero.")
except ValueError:
    print("Invalid input. Please enter a number.")

# Using finally block
try:
    # file = open("example.txt", "r")
    # data = file.read()
    pass
except FileNotFoundError:
    print("File not found.")
finally:
    # file.close()  # Ensures the file is closed
    pass

# Raising custom exceptions
def check_age(age):
    if age < 0:
        raise ValueError("Age cannot be negative.")
    else:
        print("Valid age")

try:
    check_age(-1)
except ValueError as e:
    print(e)

Enter a number: 12
Result: 0.8333333333333334
Age cannot be negative.


In [ ]:
def convert_length(value, from_unit, to_unit):
    """
    Converts length between meters and feet.

    Parameters:
        value (float): The value to convert
        from_unit (str): The unit to convert from ('m' or 'ft')
        to_unit (str): The unit to convert to ('m' or 'ft')

    Returns:
        float: The converted value
    """
    if from_unit == 'm' and to_unit == 'ft':
        return value * 3.28084
    elif from_unit == 'ft' and to_unit == 'm':
        return value / 3.28084
    else:
        raise ValueError("Invalid conversion units")

def convert_weight(value, from_unit, to_unit):
    """
    Converts weight between kilograms and pounds.

    Parameters:
        value (float): The value to convert
        from_unit (str): The unit to convert from ('kg' or 'lbs')
        to_unit (str): The unit to convert to ('kg' or 'lbs')

    Returns:
        float: The converted value
    """
    if from_unit == 'kg' and to_unit == 'lbs':
        return value * 2.20462
    elif from_unit == 'lbs' and to_unit == 'kg':
        return value / 2.20462
    else:
        raise ValueError("Invalid conversion units")

def convert_volume(value, from_unit, to_unit):
    """
    Converts volume between liters and gallons.

    Parameters:
        value (float): The value to convert
        from_unit (str): The unit to convert from ('L' or 'gal')
        to_unit (str): The unit to convert to ('L' or 'gal')

    Returns:
        float: The converted value
    """
    if from_unit == 'L' and to_unit == 'gal':
        return value * 0.264172
    elif from_unit == 'gal' and to_unit == 'L':
        return value / 0.264172
    else:
        raise ValueError("Invalid conversion units")

def unit_converter():
    """
    Main unit converter program that handles user interaction.
    """
    print("=== Unit Converter ===")
    print("1. Length (meters ↔ feet)")
    print("2. Weight (kilograms ↔ pounds)")
    print("3. Volume (liters ↔ gallons)")

    try:
        choice = input("\nChoose conversion type (1-3): ")

        if choice == '1':
            print("\n1. Meters to Feet")
            print("2. Feet to Meters")
            sub_choice = input("Choose (1 or 2): ")
            value = float(input("Enter value: "))

            if sub_choice == '1':
                result = convert_length(value, 'm', 'ft')
                print(f"{value} meters = {result:.2f} feet")
            elif sub_choice == '2':
                result = convert_length(value, 'ft', 'm')
                print(f"{value} feet = {result:.2f} meters")
            else:
                print("Invalid choice")

        elif choice == '2':
            print("\n1. Kilograms to Pounds")
            print("2. Pounds to Kilograms")
            sub_choice = input("Choose (1 or 2): ")
            value = float(input("Enter value: "))

            if sub_choice == '1':
                result = convert_weight(value, 'kg', 'lbs')
                print(f"{value} kg = {result:.2f} lbs")
            elif sub_choice == '2':
                result = convert_weight(value, 'lbs', 'kg')
                print(f"{value} lbs = {result:.2f} kg")
            else:
                print("Invalid choice")

        elif choice == '3':
            print("\n1. Liters to Gallons")
            print("2. Gallons to Liters")
            sub_choice = input("Choose (1 or 2): ")
            value = float(input("Enter value: "))

            if sub_choice == '1':
                result = convert_volume(value, 'L', 'gal')
                print(f"{value} L = {result:.2f} gallons")
            elif sub_choice == '2':
                result = convert_volume(value, 'gal', 'L')
                print(f"{value} gallons = {result:.2f} L")
            else:
                print("Invalid choice")
        else:
            print("Invalid conversion type")

    except ValueError as e:
        print(f"Error: Invalid input - {e}")
    except Exception as e:
        print(f"An error occurred: {e}")

# Run the converter
unit_converter()  # Uncomment to run interactively

=== Unit Converter ===
1. Length (meters ↔ feet)
2. Weight (kilograms ↔ pounds)
3. Volume (liters ↔ gallons)

Choose conversion type (1-3): 1

1. Meters to Feet
2. Feet to Meters
Choose (1 or 2): 1
Enter value: 60
60.0 meters = 196.85 feet


In [ ]:
def calculate_sum(numbers):
    """
    Calculate the sum of a list of numbers.

    Parameters:
        numbers (list): List of numeric values

    Returns:
        float: Sum of all numbers
    """
    return sum(numbers)

def calculate_average(numbers):
    """
    Calculate the average of a list of numbers.

    Parameters:
        numbers (list): List of numeric values

    Returns:
        float: Average of all numbers
    """
    if len(numbers) == 0:
        raise ValueError("Cannot calculate average of empty list")
    return sum(numbers) / len(numbers)

def find_maximum(numbers):
    """
    Find the maximum value in a list of numbers.

    Parameters:
        numbers (list): List of numeric values

    Returns:
        float: Maximum value
    """
    if len(numbers) == 0:
        raise ValueError("Cannot find maximum of empty list")
    return max(numbers)

def find_minimum(numbers):
    """
    Find the minimum value in a list of numbers.

    Parameters:
        numbers (list): List of numeric values

    Returns:
        float: Minimum value
    """
    if len(numbers) == 0:
        raise ValueError("Cannot find minimum of empty list")
    return min(numbers)

def math_operations_program():
    """
    Main program for performing mathematical operations on lists.
    """
    print("=== Mathematical Operations ===")
    print("1. Sum")
    print("2. Average")
    print("3. Maximum")
    print("4. Minimum")

    try:
        choice = input("\nChoose operation (1-4): ")

        # Get input from user
        numbers_input = input("Enter numbers separated by spaces: ")
        numbers = [float(x) for x in numbers_input.split()]

        if len(numbers) == 0:
            print("Error: No numbers provided")
            return

        if choice == '1':
            result = calculate_sum(numbers)
            print(f"Sum: {result}")
        elif choice == '2':
            result = calculate_average(numbers)
            print(f"Average: {result:.2f}")
        elif choice == '3':
            result = find_maximum(numbers)
            print(f"Maximum: {result}")
        elif choice == '4':
            result = find_minimum(numbers)
            print(f"Minimum: {result}")
        else:
            print("Invalid operation choice")

    except ValueError as e:
        print(f"Error: Invalid input - {e}")
    except Exception as e:
        print(f"An error occurred: {e}")

# Run the program
math_operations_program()  # Uncomment to run interactively

=== Mathematical Operations ===
1. Sum
2. Average
3. Maximum
4. Minimum

Choose operation (1-4): 3
Enter numbers separated by spaces: 12 13 14 6
Maximum: 14.0


In [ ]:
# Problem 1: Extract Every Other Element
def extract_every_other(lst):
    """
    Extracts every other element from a list, starting from the first element.

    Parameters:
        lst (list): Input list

    Returns:
        list: List containing every other element
    """
    return lst[::2]

# Test
print("Problem 1:", extract_every_other([1, 2, 3, 4, 5, 6]))  # [1, 3, 5]


# Problem 2: Slice a Sublist
def get_sublist(lst, start, end):
    """
    Returns a sublist from a given list.

    Parameters:
        lst (list): Input list
        start (int): Starting index
        end (int): Ending index (inclusive)

    Returns:
        list: Sublist from start to end
    """
    return lst[start:end+1]

# Test
print("Problem 2:", get_sublist([1, 2, 3, 4, 5, 6], 2, 4))  # [3, 4, 5]


# Problem 3: Reverse a List Using Slicing
def reverse_list(lst):
    """
    Reverses a list using slicing.

    Parameters:
        lst (list): Input list

    Returns:
        list: Reversed list
    """
    return lst[::-1]

# Test
print("Problem 3:", reverse_list([1, 2, 3, 4, 5]))  # [5, 4, 3, 2, 1]


# Problem 4: Remove First and Last Elements
def remove_first_last(lst):
    """
    Removes the first and last elements of a list.

    Parameters:
        lst (list): Input list

    Returns:
        list: List without first and last elements
    """
    return lst[1:-1]

# Test
print("Problem 4:", remove_first_last([1, 2, 3, 4, 5]))  # [2, 3, 4]


# Problem 5: Get First n Elements
def get_first_n(lst, n):
    """
    Extracts the first n elements from a list.

    Parameters:
        lst (list): Input list
        n (int): Number of elements to extract

    Returns:
        list: First n elements
    """
    return lst[:n]

# Test
print("Problem 5:", get_first_n([1, 2, 3, 4, 5], 3))  # [1, 2, 3]


# Problem 6: Extract Elements from the End
def get_last_n(lst, n):
    """
    Extracts the last n elements of a list.

    Parameters:
        lst (list): Input list
        n (int): Number of elements to extract

    Returns:
        list: Last n elements
    """
    return lst[-n:]

# Test
print("Problem 6:", get_last_n([1, 2, 3, 4, 5], 2))  # [4, 5]


# Problem 7: Extract Elements in Reverse Order
def reverse_skip(lst):
    """
    Extracts elements in reverse order, starting from second-to-last,
    skipping one element in between.

    Parameters:
        lst (list): Input list

    Returns:
        list: Elements in reverse order with skipping
    """
    return lst[-2::-2]

# Test
print("Problem 7:", reverse_skip([1, 2, 3, 4, 5, 6]))  # [5, 3, 1]

Problem 1: [1, 3, 5]
Problem 2: [3, 4, 5]
Problem 3: [5, 4, 3, 2, 1]
Problem 4: [2, 3, 4]
Problem 5: [1, 2, 3]
Problem 6: [4, 5]
Problem 7: [5, 3, 1]


In [ ]:
# Problem 1: Flatten a Nested List
def flatten(lst):
    """
    Flattens a nested list into a single list.

    Parameters:
        lst (list): Nested list

    Returns:
        list: Flattened list
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(flatten(item))
        else:
            result.append(item)
    return result

# Test
print("Problem 1:", flatten([[1, 2], [3, 4], [5]]))  # [1, 2, 3, 4, 5]


# Problem 2: Accessing Nested List Elements
def access_nested_element(lst, indices):
    """
    Extracts a specific element from a nested list given its indices.

    Parameters:
        lst (list): Nested list
        indices (list): List of indices

    Returns:
        any: Element at the specified position
    """
    result = lst
    for index in indices:
        result = result[index]
    return result

# Test
print("Problem 2:", access_nested_element([[1, 2, 3], [4, 5, 6], [7, 8, 9]], [1, 2]))  # 6


# Problem 3: Sum of All Elements in a Nested List
def sum_nested(lst):
    """
    Calculates the sum of all numbers in a nested list.

    Parameters:
        lst (list): Nested list

    Returns:
        int/float: Sum of all elements
    """
    total = 0
    for item in lst:
        if isinstance(item, list):
            total += sum_nested(item)
        else:
            total += item
    return total

# Test
print("Problem 3:", sum_nested([[1, 2], [3, [4, 5]], 6]))  # 21


# Problem 4: Remove Specific Element from a Nested List
def remove_element(lst, elem):
    """
    Removes all occurrences of a specific element from a nested list.

    Parameters:
        lst (list): Nested list
        elem (any): Element to remove

    Returns:
        list: Modified list
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            cleaned = remove_element(item, elem)
            if cleaned:  # Only add non-empty lists
                result.append(cleaned)
        elif item != elem:
            result.append(item)
    return result

# Test
print("Problem 4:", remove_element([[1, 2], [3, 2], [4, 5]], 2))  # [[1], [3], [4, 5]]


# Problem 5: Find Maximum Element in a Nested List
def find_max(lst):
    """
    Finds the maximum element in a nested list.

    Parameters:
        lst (list): Nested list

    Returns:
        int/float: Maximum element
    """
    flat = flatten(lst)
    return max(flat)

# Test
print("Problem 5:", find_max([[1, 2], [3, [4, 5]], 6]))  # 6


# Problem 6: Count Occurrences of an Element in a Nested List
def count_occurrences(lst, elem):
    """
    Counts how many times a specific element appears in a nested list.

    Parameters:
        lst (list): Nested list
        elem (any): Element to count

    Returns:
        int: Count of occurrences
    """
    count = 0
    for item in lst:
        if isinstance(item, list):
            count += count_occurrences(item, elem)
        elif item == elem:
            count += 1
    return count

# Test
print("Problem 6:", count_occurrences([[1, 2], [2, 3], [2, 4]], 2))  # 3


# Problem 7: Flatten a List of Lists of Lists
def deep_flatten(lst):
    """
    Flattens a deeply nested list into a single list.

    Parameters:
        lst (list): Deeply nested list

    Returns:
        list: Single flattened list
    """
    result = []
    for item in lst:
        if isinstance(item, list):
            result.extend(deep_flatten(item))
        else:
            result.append(item)
    return result

# Test
print("Problem 7:", deep_flatten([[[1, 2], [3, 4]], [[5, 6], [7, 8]]]))  # [1, 2, 3, 4, 5, 6, 7, 8]


# Problem 8: Nested List Average
def average_nested(lst):
    """
    Calculates the average of all elements in a nested list.

    Parameters:
        lst (list): Nested list

    Returns:
        float: Average of all elements
    """
    flat = flatten(lst)
    return sum(flat) / len(flat)

# Test
print("Problem 8:", average_nested([[1, 2], [3, 4], [5, 6]]))  # 3.5

Problem 1: [1, 2, 3, 4, 5]
Problem 2: 6
Problem 3: 21
Problem 4: [[1], [3], [4, 5]]
Problem 5: 6
Problem 6: 3
Problem 7: [1, 2, 3, 4, 5, 6, 7, 8]
Problem 8: 3.5


In [ ]:
import numpy as np

# Import NumPy and create arrays of zeros
zeros_arr = np.zeros((2, 3))
print("A zeros array is \n", zeros_arr, "with dimensions", zeros_arr.shape, "\n")

# Create different dimensional arrays
zero_dim_array = np.array(5)
one_dim_array = np.array([1, 2, 3])
n_dim_array = np.array([[1, 2], [3, 4]])

for arr in [zero_dim_array, one_dim_array, n_dim_array]:
    print(f"Array:\n{arr}\nDimension: {arr.ndim}\nData type: {arr.dtype}\n")

A zeros array is 
 [[0. 0. 0.]
 [0. 0. 0.]] with dimensions (2, 3) 

Array:
5
Dimension: 0
Data type: int64

Array:
[1 2 3]
Dimension: 1
Data type: int64

Array:
[[1 2]
 [3 4]]
Dimension: 2
Data type: int64



In [ ]:
import numpy as np

# 1D Array
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D Array:")
print("ndim:", arr_1d.ndim)  # 1
print("shape:", arr_1d.shape)  # (5,)
print("size:", arr_1d.size)  # 5
print("dtype:", arr_1d.dtype)  # int64
print("itemsize:", arr_1d.itemsize)  # 8
print("nbytes:", arr_1d.nbytes)  # 40

# 2D Array
arr_2d = np.array([[1, 2, 3], [4, 5, 6]])
print("\n2D Array:")
print("ndim:", arr_2d.ndim)  # 2
print("shape:", arr_2d.shape)  # (2, 3)
print("size:", arr_2d.size)  # 6
print("Transpose:\n", arr_2d.T)

# 3D Array
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print("\n3D Array:")
print("ndim:", arr_3d.ndim)  # 3
print("shape:", arr_3d.shape)  # (2, 2, 3)
print("size:", arr_3d.size)  # 12

1D Array:
ndim: 1
shape: (5,)
size: 5
dtype: int64
itemsize: 8
nbytes: 40

2D Array:
ndim: 2
shape: (2, 3)
size: 6
Transpose:
 [[1 4]
 [2 5]
 [3 6]]

3D Array:
ndim: 3
shape: (2, 2, 3)
size: 12


In [ ]:
import numpy as np

# Create an array with shape (2, 3)
array = np.array([[1, 2, 3], [4, 5, 6]])

# Reshape to (3, 2)
reshaped_array = array.reshape(3, 2)
print("Original Shape:", array.shape, "\nReshaped Shape:", reshaped_array.shape)
print("Reshaped array:\n", reshaped_array)

Original Shape: (2, 3) 
Reshaped Shape: (3, 2)
Reshaped array:
 [[1 2]
 [3 4]
 [5 6]]


In [ ]:
import numpy as np

# Using arange
a = np.arange(1, 10)
print("arange(1, 10):", a)

x = np.arange(10.4)
print("arange(10.4):", x)

x = np.arange(0.5, 10.4, 0.8)
print("arange(0.5, 10.4, 0.8):", x)

# Using linspace
print("\nlinspace(1, 10):", np.linspace(1, 10))
print("linspace(1, 10, 7):", np.linspace(1, 10, 7))
print("linspace(1, 10, 7, endpoint=False):", np.linspace(1, 10, 7, endpoint=False))

# Creating arrays with ones, zeros, empty
ones_array = np.ones((2, 3))
zeros_array = np.zeros((3, 2))
empty_array = np.empty((2, 2))
identity_matrix = np.eye(3)

print("\nOnes array:\n", ones_array)
print("Zeros array:\n", zeros_array)
print("Identity matrix:\n", identity_matrix)

# From existing arrays
array_from_list = np.array([1, 2, 3])
array_from_tuple = np.array((4, 5, 6))
array_from_nested_list = np.array([[1, 2, 3], [4, 5, 6]])

print("\nFrom list:", array_from_list)
print("From tuple:", array_from_tuple)
print("From nested list:\n", array_from_nested_list)

arange(1, 10): [1 2 3 4 5 6 7 8 9]
arange(10.4): [ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
arange(0.5, 10.4, 0.8): [ 0.5  1.3  2.1  2.9  3.7  4.5  5.3  6.1  6.9  7.7  8.5  9.3 10.1]

linspace(1, 10): [ 1.          1.18367347  1.36734694  1.55102041  1.73469388  1.91836735
  2.10204082  2.28571429  2.46938776  2.65306122  2.83673469  3.02040816
  3.20408163  3.3877551   3.57142857  3.75510204  3.93877551  4.12244898
  4.30612245  4.48979592  4.67346939  4.85714286  5.04081633  5.2244898
  5.40816327  5.59183673  5.7755102   5.95918367  6.14285714  6.32653061
  6.51020408  6.69387755  6.87755102  7.06122449  7.24489796  7.42857143
  7.6122449   7.79591837  7.97959184  8.16326531  8.34693878  8.53061224
  8.71428571  8.89795918  9.08163265  9.26530612  9.44897959  9.63265306
  9.81632653 10.        ]
linspace(1, 10, 7): [ 1.   2.5  4.   5.5  7.   8.5 10. ]
linspace(1, 10, 7, endpoint=False): [1.         2.28571429 3.57142857 4.85714286 6.14285714 7.42857143
 8.71428571]

Ones array:
 

In [ ]:
import numpy as np

arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Horizontal stacking
hstacked = np.hstack((arr1, arr2))
print("Horizontal stack:\n", hstacked)

# Vertical stacking
vstacked = np.vstack((arr1, arr2))
print("\nVertical stack:\n", vstacked)

# Concatenation
concat_axis0 = np.concatenate((arr1, arr2), axis=0)
concat_axis1 = np.concatenate((arr1, arr2), axis=1)
print("\nConcatenate axis=0:\n", concat_axis0)
print("\nConcatenate axis=1:\n", concat_axis1)

Horizontal stack:
 [[1 2 5 6]
 [3 4 7 8]]

Vertical stack:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenate axis=0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenate axis=1:
 [[1 2 5 6]
 [3 4 7 8]]


In [ ]:
import numpy as np

# 2D Array indexing
array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

print("Element [0, 1]:", array[0, 1])  # 2
print("Element [-1, -1]:", array[-1, -1])  # 9
print("Slice [0:2, 1:3]:\n", array[0:2, 1:3])

# Boolean indexing
print("\nElements > 5:", array[array > 5])

# Integer indexing
rows = np.array([0, 2])
cols = np.array([1, 2])
print("Integer indexing:", array[rows, cols])

Element [0, 1]: 2
Element [-1, -1]: 9
Slice [0:2, 1:3]:
 [[2 3]
 [5 6]]

Elements > 5: [6 7 8 9]
Integer indexing: [2 9]


In [ ]:
import numpy as np

# Universal functions
arr = np.array([1, 4, 9, 16])

squared = np.square(arr)
sqrt = np.sqrt(arr)

print("Squared:", squared)
print("Square root:", sqrt)

# Trigonometric functions
angles = np.array([0, np.pi/4, np.pi/2])
sine_values = np.sin(angles)
print("\nSine values:", sine_values)

# Linear algebra
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# Matrix multiplication
product = np.dot(A, B)
print("\nMatrix product:\n", product)

# Determinant
det = np.linalg.det(A)
print("Determinant:", det)

# Inverse
inverse = np.linalg.inv(A)
print("Inverse:\n", inverse)

# Eigenvalues and eigenvectors
eigvals, eigvecs = np.linalg.eig(A)
print("Eigenvalues:", eigvals)
print("Eigenvectors:\n", eigvecs)

Squared: [  1  16  81 256]
Square root: [1. 2. 3. 4.]

Sine values: [0.         0.70710678 1.        ]

Matrix product:
 [[19 22]
 [43 50]]
Determinant: -2.0000000000000004
Inverse:
 [[-2.   1. ]
 [ 1.5 -0.5]]
Eigenvalues: [-0.37228132  5.37228132]
Eigenvectors:
 [[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
import numpy as np

# Valid broadcasting - column matches
A = np.array([[1], [2], [3]])  # Shape (3,1)
B = np.array([10, 20, 30])  # Shape (3,)
C = A + B  # Works! Result shape: (3,3)
print("Broadcasting result:\n", C)

# Valid broadcasting - row matches
A = np.array([[1, 2, 3]])  # Shape (1,3)
B = np.array([[4], [5], [6]])  # Shape (3,1)
C = A + B  # Works! Result shape: (3,3)
print("\nBroadcasting result 2:\n", C)

Broadcasting result:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]

Broadcasting result 2:
 [[5 6 7]
 [6 7 8]
 [7 8 9]]


In [ ]:
import numpy as np
import time

# Create two large arrays
size = 10**6
a = np.random.rand(size)
b = np.random.rand(size)

# Using a loop
start_time = time.time()
result_loop = np.zeros(size)
for i in range(size):
    result_loop[i] = a[i] + b[i]
end_time = time.time()
loop_time = end_time - start_time
print(f"Loop Execution Time: {loop_time:.5f} seconds")

# Using NumPy's vectorized operations
start_time = time.time()
result_vectorized = a + b
end_time = time.time()
vectorized_time = end_time - start_time
print(f"Vectorized Execution Time: {vectorized_time:.5f} seconds")

# Performance improvement
speedup = loop_time / vectorized_time
print(f"Vectorization is approximately {speedup:.2f} times faster!")

Loop Execution Time: 1.01186 seconds
Vectorized Execution Time: 0.01901 seconds
Vectorization is approximately 53.22 times faster!


In [ ]:
import numpy as np

# 1. Initialize an empty array with size 2x2
empty_arr = np.empty((2, 2))
print("1. Empty 2x2 array:\n", empty_arr)

# 2. Initialize an all one array with size 4x2
ones_arr = np.ones((4, 2))
print("\n2. Ones 4x2 array:\n", ones_arr)

# 3. Return a new array filled with fill value
filled_arr = np.full((3, 3), 7)
print("\n3. Array filled with 7:\n", filled_arr)

# 4. Return zeros with same shape as given array
sample_arr = np.array([[1, 2, 3], [4, 5, 6]])
zeros_like_arr = np.zeros_like(sample_arr)
print("\n4. Zeros like sample array:\n", zeros_like_arr)

# 5. Return ones with same shape as given array
ones_like_arr = np.ones_like(sample_arr)
print("\n5. Ones like sample array:\n", ones_like_arr)

# 6. Convert list to numpy array
new_list = [1, 2, 3, 4]
np_array = np.array(new_list)
print("\n6. Converted array:", np_array)

1. Empty 2x2 array:
 [[2.5e-323 3.0e-323]
 [3.5e-323 4.0e-323]]

2. Ones 4x2 array:
 [[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]

3. Array filled with 7:
 [[7 7 7]
 [7 7 7]
 [7 7 7]]

4. Zeros like sample array:
 [[0 0 0]
 [0 0 0]]

5. Ones like sample array:
 [[1 1 1]
 [1 1 1]]

6. Converted array: [1 2 3 4]


In [ ]:
import numpy as np

# 1. Create array with values from 10 to 49
arr_range = np.arange(10, 50)
print("1. Array from 10 to 49:", arr_range)

# 2. Create 3x3 matrix with values from 0 to 8
matrix_3x3 = np.arange(9).reshape(3, 3)
print("\n2. 3x3 matrix:\n", matrix_3x3)

# 3. Create 3x3 identity matrix
identity = np.eye(3)
print("\n3. 3x3 identity matrix:\n", identity)

# 4. Create random array of size 30 and find mean
random_arr = np.random.random(30)
mean_val = random_arr.mean()
print("\n4. Mean of random array:", mean_val)

# 5. Create 10x10 array with random values and find min/max
random_10x10 = np.random.random((10, 10))
min_val = random_10x10.min()
max_val = random_10x10.max()
print("\n5. Min:", min_val, "Max:", max_val)

# 6. Create zero array of size 10 and replace 5th element with 1
zero_arr = np.zeros(10)
zero_arr[4] = 1
print("\n6. Array with 5th element as 1:", zero_arr)

# 7. Reverse an array
arr = np.array([1, 2, 0, 0, 4, 0])
reversed_arr = arr[::-1]
print("\n7. Reversed array:", reversed_arr)

# 8. Create 2d array with 1 on border and 0 inside
border_arr = np.ones((5, 5))
border_arr[1:-1, 1:-1] = 0
print("\n8. Border array:\n", border_arr)

# 9. Create 8x8 matrix with checkerboard pattern
checkerboard = np.zeros((8, 8), dtype=int)
checkerboard[1::2, ::2] = 1
checkerboard[::2, 1::2] = 1
print("\n9. Checkerboard pattern:\n", checkerboard)

1. Array from 10 to 49: [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]

2. 3x3 matrix:
 [[0 1 2]
 [3 4 5]
 [6 7 8]]

3. 3x3 identity matrix:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

4. Mean of random array: 0.46822264680282966

5. Min: 0.02827325103846967 Max: 0.9990952753044509

6. Array with 5th element as 1: [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]

7. Reversed array: [0 4 0 0 2 1]

8. Border array:
 [[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]

9. Checkerboard pattern:
 [[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [ ]:
import numpy as np

x = np.array([[1, 2], [3, 5]])
y = np.array([[5, 6], [7, 8]])
v = np.array([9, 10])
w = np.array([11, 12])

# 1. Add arrays
add_result = x + y
print("1. Addition:\n", add_result)

# 2. Subtract arrays
sub_result = x - y
print("\n2. Subtraction:\n", sub_result)

# 3. Multiply by integer
mult_result = x * 3
print("\n3. Multiply by 3:\n", mult_result)

# 4. Square of each element
square_result = np.square(x)
print("\n4. Square:\n", square_result)

# 5. Dot products
dot_vw = np.dot(v, w)
dot_xv = np.dot(x, v)
dot_xy = np.dot(x, y)
print("\n5. Dot product v and w:", dot_vw)
print("Dot product x and v:", dot_xv)
print("Dot product x and y:\n", dot_xy)

# 6. Concatenate
concat_row = np.vstack((x, y))
concat_col = np.column_stack((v, w))
print("\n6. Concatenate x and y (rows):\n", concat_row)
print("Concatenate v and w (columns):\n", concat_col)

# 7. Try concatenating x and v (will cause error if not reshaped)
print("\n7. Attempting to concatenate x and v:")
try:
    result = np.concatenate((x, v))
    print("Success:", result)
except ValueError as e:
    print(f"Error: {e}")
    print("Explanation: Arrays have incompatible shapes. x is 2D (2,2) and v is 1D (2,).")
    print("Solution: Reshape v to match x's dimension structure")
    v_reshaped = v.reshape(1, 2)
    result = np.vstack((x, v_reshaped))
    print("After reshaping:\n", result)

1. Addition:
 [[ 6  8]
 [10 13]]

2. Subtraction:
 [[-4 -4]
 [-4 -3]]

3. Multiply by 3:
 [[ 3  6]
 [ 9 15]]

4. Square:
 [[ 1  4]
 [ 9 25]]

5. Dot product v and w: 219
Dot product x and v: [29 77]
Dot product x and y:
 [[19 22]
 [50 58]]

6. Concatenate x and y (rows):
 [[1 2]
 [3 5]
 [5 6]
 [7 8]]
Concatenate v and w (columns):
 [[ 9 11]
 [10 12]]

7. Attempting to concatenate x and v:
Error: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)
Explanation: Arrays have incompatible shapes. x is 2D (2,2) and v is 1D (2,).
Solution: Reshape v to match x's dimension structure
After reshaping:
 [[ 1  2]
 [ 3  5]
 [ 9 10]]


In [ ]:
import numpy as np

A = np.array([[3, 4], [7, 8]])
B = np.array([[5, 3], [2, 1]])

# 1. Prove A.A^-1 = I
A_inv = np.linalg.inv(A)
identity_result = np.dot(A, A_inv)
print("1. A * A^-1 =\n", identity_result)
print("Is it identity?", np.allclose(identity_result, np.eye(2)))

# 2. Prove AB ≠ BA
AB = np.dot(A, B)
BA = np.dot(B, A)
print("\n2. AB =\n", AB)
print("BA =\n", BA)
print("AB ≠ BA?", not np.allclose(AB, BA))

# 3. Prove (AB)^T = B^T A^T
AB_T = AB.T
B_T_A_T = np.dot(B.T, A.T)
print("\n3. (AB)^T =\n", AB_T)
print("B^T A^T =\n", B_T_A_T)
print("Are they equal?", np.allclose(AB_T, B_T_A_T))

# Solve system of linear equations
# 2x - 3y + z = -1
# x - y + 2z = -3
# 3x + y - z = 9

# Coefficient matrix
A_sys = np.array([[2, -3, 1],
                   [1, -1, 2],
                   [3, 1, -1]])

# Constants vector
B_sys = np.array([-1, -3, 9])

# Solve using inverse method
A_sys_inv = np.linalg.inv(A_sys)
X_inv = np.dot(A_sys_inv, B_sys)
print("\n4. Solution using inverse method:")
print(f"x = {X_inv[0]:.2f}, y = {X_inv[1]:.2f}, z = {X_inv[2]:.2f}")

# Solve using np.linalg.solve
X_solve = np.linalg.solve(A_sys, B_sys)
print("\nSolution using np.linalg.solve:")
print(f"x = {X_solve[0]:.2f}, y = {X_solve[1]:.2f}, z = {X_solve[2]:.2f}")

# Verify solution
verification = np.dot(A_sys, X_solve)
print("\nVerification (should equal B):", verification)
print("Original B:", B_sys)
print("Match?", np.allclose(verification, B_sys))

1. A * A^-1 =
 [[1.00000000e+00 0.00000000e+00]
 [1.77635684e-15 1.00000000e+00]]
Is it identity? True

2. AB =
 [[23 13]
 [51 29]]
BA =
 [[36 44]
 [13 16]]
AB ≠ BA? True

3. (AB)^T =
 [[23 51]
 [13 29]]
B^T A^T =
 [[23 51]
 [13 29]]
Are they equal? True

4. Solution using inverse method:
x = 2.00, y = 1.00, z = -2.00

Solution using np.linalg.solve:
x = 2.00, y = 1.00, z = -2.00

Verification (should equal B): [-1. -3.  9.]
Original B: [-1 -3  9]
Match? True


In [ ]:
import numpy as np
import time

size = 1000000

# Create test data
list1 = list(range(size))
list2 = list(range(size))
arr1 = np.array(list1)
arr2 = np.array(list2)

print("=== Performance Comparison: Python Lists vs NumPy Arrays ===\n")

# 1. Element-wise Addition
print("1. ELEMENT-WISE ADDITION")
print("-" * 50)

# Python lists
start = time.time()
result_list = [list1[i] + list2[i] for i in range(size)]
end = time.time()
list_add_time = end - start
print(f"Python lists: {list_add_time:.5f} seconds")

# NumPy arrays
start = time.time()
result_np = arr1 + arr2
end = time.time()
np_add_time = end - start
print(f"NumPy arrays: {np_add_time:.5f} seconds")
print(f"Speedup: {list_add_time/np_add_time:.2f}x faster\n")

# 2. Element-wise Multiplication
print("2. ELEMENT-WISE MULTIPLICATION")
print("-" * 50)

# Python lists
start = time.time()
result_list = [list1[i] * list2[i] for i in range(size)]
end = time.time()
list_mult_time = end - start
print(f"Python lists: {list_mult_time:.5f} seconds")

# NumPy arrays
start = time.time()
result_np = arr1 * arr2
end = time.time()
np_mult_time = end - start
print(f"NumPy arrays: {np_mult_time:.5f} seconds")
print(f"Speedup: {list_mult_time/np_mult_time:.2f}x faster\n")

# 3. Dot Product
print("3. DOT PRODUCT")
print("-" * 50)

# Python lists
start = time.time()
result_list = sum([list1[i] * list2[i] for i in range(size)])
end = time.time()
list_dot_time = end - start
print(f"Python lists: {list_dot_time:.5f} seconds")

# NumPy arrays
start = time.time()
result_np = np.dot(arr1, arr2)
end = time.time()
np_dot_time = end - start
print(f"NumPy arrays: {np_dot_time:.5f} seconds")
print(f"Speedup: {list_dot_time/np_dot_time:.2f}x faster\n")

# 4. Matrix Multiplication
print("4. MATRIX MULTIPLICATION (1000x1000)")
print("-" * 50)

matrix_size = 1000
matrix_list1 = [[i+j for j in range(matrix_size)] for i in range(matrix_size)]
matrix_list2 = [[i-j for j in range(matrix_size)] for i in range(matrix_size)]
matrix_np1 = np.array(matrix_list1)
matrix_np2 = np.array(matrix_list2)

# Python lists (simplified matrix multiplication)
start = time.time()
result_matrix = [[sum(matrix_list1[i][k] * matrix_list2[k][j]
                      for k in range(matrix_size))
                  for j in range(matrix_size)]
                 for i in range(matrix_size)]
end = time.time()
list_matrix_time = end - start
print(f"Python lists: {list_matrix_time:.5f} seconds")

# NumPy arrays
start = time.time()
result_np_matrix = np.dot(matrix_np1, matrix_np2)
end = time.time()
np_matrix_time = end - start
print(f"NumPy arrays: {np_matrix_time:.5f} seconds")
print(f"Speedup: {list_matrix_time/np_matrix_time:.2f}x faster\n")

# Summary
print("=" * 50)
print("SUMMARY")
print("=" * 50)
print(f"Average speedup: {np.mean([list_add_time/np_add_time, list_mult_time/np_mult_time, list_dot_time/np_dot_time, list_matrix_time/np_matrix_time]):.2f}x")
print("\nNumPy is significantly faster due to:")
print("  - Vectorized operations")
print("  - Optimized C/Fortran implementations")
print("  - Efficient memory management")
print("  - Elimination of Python loops")

=== Performance Comparison: Python Lists vs NumPy Arrays ===

1. ELEMENT-WISE ADDITION
--------------------------------------------------
Python lists: 0.10621 seconds
NumPy arrays: 0.00654 seconds
Speedup: 16.23x faster

2. ELEMENT-WISE MULTIPLICATION
--------------------------------------------------
Python lists: 0.13724 seconds
NumPy arrays: 0.00386 seconds
Speedup: 35.51x faster

3. DOT PRODUCT
--------------------------------------------------
Python lists: 0.15726 seconds
NumPy arrays: 0.00260 seconds
Speedup: 60.39x faster

4. MATRIX MULTIPLICATION (1000x1000)
--------------------------------------------------
Python lists: 210.63978 seconds
NumPy arrays: 2.31078 seconds
Speedup: 91.16x faster

SUMMARY
Average speedup: 50.82x

NumPy is significantly faster due to:
  - Vectorized operations
  - Optimized C/Fortran implementations
  - Efficient memory management
  - Elimination of Python loops
